version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  app:
    build: .
    ports:
      - '80:1234'
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 1234
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/todo-api
    depends_on:
      - mongo

volumes:
  mongo: {}
